### ISSUE TITLE
Activating 'taskbar' module crashes the app on launch

### ISSUE THREAD

**Issue by msulli888** [blahsd/snwe#39]
First launch was fine, once I changed the settings it started throwing the following exception.
I think it was down to the taskbar option
```Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from null
    at EventEmitter.ipcMain.on (/Applications/snwe.app/Contents/Resources/app/main.js:13:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Applications/snwe.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)```

**Comment by blahsd** [comment]
Fuck meeeee. I have no clue why it would do that. First off, which version are you using? Compiled or command line? Second, could you try nuking your ~/Library/Application Support/snwe folder? This would let you start anew with preferences. 

After you delete that folder it should work again. Ideally, you could note down each step you take since then, so I can try to reproduce the error, and start there to fix it.

**Comment by msulli888** [comment]
I can't recreate it myself now :D. I just did a fresh reinstall and it seemed to work

**Comment by blahsd** [comment]
Good to hear!
