### ISSUE TITLE
Got "A Javascript error occured in the main process"

### ISSUE THREAD

**Issue by binamkayastha** [blahsd/snwe#42]
I think this happened because I used command-Q to try exit out of the settings menu. I tried uninstalling and reinstalling the app, but it gave the same error. I tried to remove the files in /private folder, but it has read-only permissions, and I can't `chmod` it for some reason.

```Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from null
    at EventEmitter.ipcMain.on (/private/var/folders/mm/yv6bk_815zg78z6l4rzfzllc0000gp/T/AppTranslocation/7A927F6B-C899-4E4F-A7DA-0D1E15EFA5C0/d/snwe.app/Contents/Resources/app/main.js:13:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/private/var/folders/mm/yv6bk_815zg78z6l4rzfzllc0000gp/T/AppTranslocation/7A927F6B-C899-4E4F-A7DA-0D1E15EFA5C0/d/snwe.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)```

**Comment by binamkayastha** [comment]
Lol, just grabbed the "fix" from #39
At least you have something more reproducible hopefully?

**Comment by blahsd** [comment]
Yes! Thanks! Will try to figure this out. But you have it working correctly as of right now, right?

**Comment by binamkayastha** [comment]
Yup! I just clear that folder when that happens. Although I loose all my configs when I do it :(

**Comment by blahsd** [comment]
I'm not sure at which point this happened, but I'm not running into this anymore. Are you?

**Comment by blahsd** [comment]
Assuming closed, feel free to reopen.
